services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: vcr
      POSTGRES_PASSWORD: vcr
      POSTGRES_DB: vans_coding_router
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
